# SPDX-FileCopyrightText: 2026 Thomas Mathys
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # build-linux:
  #   name: Linux Builds (${{matrix.c_compiler}}, ${{matrix.build_type}})
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       c_compiler: [clang, gcc]
  #       build_type: [Release, Debug]

  #   steps:

  #   - name: Set reusable strings
  #     id: strings
  #     shell: bash
  #     run: |
  #       echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

  #   - name: Checkout sources
  #     uses: actions/checkout@v6

  #   - name: Configure CMake
  #     run: >
  #       cmake
  #       -B ${{steps.strings.outputs.build-output-dir}}
  #       -S ${{github.workspace}}
  #       --preset dev-linux
  #       -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
  #       -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

  #   - name: Build
  #     run: |
  #       cmake --build ${{steps.strings.outputs.build-output-dir}} --config ${{matrix.build_type}}

  #   - name: Test
  #     working-directory: ${{steps.strings.outputs.build-output-dir}}
  #     run: ctest --build-config ${{matrix.build_type}} --output-on-failure

  # build-mingw:
  #   name: MinGW Builds (${{matrix.build_type}})
  #   runs-on: windows-latest

  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       build_type: [Release, Debug]

  #   steps:

  #   - name: Set reusable strings
  #     id: strings
  #     shell: bash
  #     run: |
  #       echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

  #   - name: Checkout sources
  #     uses: actions/checkout@v6

  #   - name: Configure CMake
  #     run: >
  #       cmake
  #       -B ${{steps.strings.outputs.build-output-dir}}
  #       -S ${{github.workspace}}
  #       -G Ninja
  #       --preset=dev-windows
  #       -DCMAKE_C_COMPILER=gcc
  #       -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

  #   - name: Build
  #     run: |
  #       cmake --build ${{steps.strings.outputs.build-output-dir}} --config ${{matrix.build_type}}

  #   - name: Test
  #     working-directory: ${{steps.strings.outputs.build-output-dir}}
  #     run: ctest --build-config ${{matrix.build_type}} --output-on-failure

  # build-windows:
  #   name: Windows Builds (${{matrix.arch}}, ${{matrix.build_type}})
  #   runs-on: windows-latest

  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       arch: [x64, Win32]
  #       build_type: [Release, Debug]

  #   steps:

  #   - name: Set reusable strings
  #     id: strings
  #     shell: bash
  #     run: |
  #       echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

  #   - name: Checkout sources
  #     uses: actions/checkout@v6

  #   - name: Configure CMake
  #     run: >
  #       cmake
  #       -B ${{steps.strings.outputs.build-output-dir}}
  #       -S ${{github.workspace}}
  #       --preset dev-windows
  #       -A ${{matrix.arch}}
  #       -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

  #   - name: Build
  #     run: |
  #       cmake --build ${{steps.strings.outputs.build-output-dir}} --config ${{matrix.build_type}}

  #   - name: Test
  #     working-directory: ${{steps.strings.outputs.build-output-dir}}
  #     run: ctest --build-config ${{matrix.build_type}} --output-on-failure

  # build-macos:
  #   name: MacOS Builds (${{matrix.build_type}})
  #   runs-on: macos-latest

  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       build_type: [Release, Debug]

  #   steps:

  #   - name: Set reusable strings
  #     id: strings
  #     shell: bash
  #     run: |
  #       echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

  #   - name: Checkout sources
  #     uses: actions/checkout@v6

  #   - name: Configure CMake
  #     run: >
  #       cmake
  #       -B ${{steps.strings.outputs.build-output-dir}}
  #       -S ${{github.workspace}}
  #       --preset dev-macos
  #       -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

  #   - name: Build
  #     run: |
  #       cmake --build ${{steps.strings.outputs.build-output-dir}} --config ${{matrix.build_type}}

  #   - name: Test
  #     working-directory: ${{steps.strings.outputs.build-output-dir}}
  #     run: ctest --build-config ${{matrix.build_type}} --output-on-failure

  # quality:
  #   name: Static Quality Checks
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: true

  #   steps:

  #   - name: Checkout sources
  #     uses: actions/checkout@v6

  #   - name: Install reuse
  #     shell: bash
  #     run: |
  #       pipx install reuse

  #   - name: Run reuse lint
  #     shell: bash
  #     run: |
  #       reuse lint

  build-cygwin:
    name: Cygwin Builds (${{matrix.build_type}})
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        build_type: [Debug] # TODO: add release build once stuff works

    steps:

    # TODO: do we need this? How can we get it to work with cygwin?
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"

    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@v6
      with:
        packages: cmake gcc-core ninja

    # TODO: This uses powershell, which I'd prefer not to use
    - name: Set Cygwin PATH
      run: echo "/usr/bin:$(cygpath C:/Windows)/system32" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    # TODO: remove this
    - name: See what I'm doing
      shell: bash
      run: where cmake gcc ninja ls

    # TODO: see what's missing here (see another build)
    # TODO: probably this is not going to work because we need to convert paths to something cygwin understands
    # TODO: seems to work, so it is just missing proper configuration or what?
    # TODO: specify generator with -G or should we just pull in a preset?
    #       => generator should go into base preset
    #       => C flags should go into a cygwin specific preset (or suppress them in our CMake script, after all this is where we mess with warnings, so it's all in one place)
    #       => Rationale: this is not github action specific, anybody building locally needs the C flags too. And frankly it does not matter to me whether I am using Ninja or make locally
    - name: Configure CMake
      shell: bash
      run: >
        cmake
        -B $(cygpath "${{steps.strings.outputs.build-output-dir}}")
        -S $(cygpath "${{github.workspace}}")
        --preset dev-linux-gcc
        -G Ninja
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        -DCMAKE_C_FLAGS=-Wno-char-subscripts

    # TODO: fully flesh this out (see another build)
    - name: Build
      shell: bash
      run: |
        cmake --build $(cygpath "${{steps.strings.outputs.build-output-dir}}") --config ${{matrix.build_type}}

    # TODO: fully flesh this out (see another build)
    # TODO: can we not pass the working directory to ctest directly?
    - name: Test
      working-directory: ${{steps.strings.outputs.build-output-dir}}
      run: ctest --build-config ${{matrix.build_type}} --output-on-failure
